apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-kunde-portal-frontend-v2
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: fint-kunde-portal-frontend-v2
    app.kubernetes.io/instance: fint-kunde-portal-frontend-v2_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: fint-core
    fintlabs.no/team: core
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8000
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-kunde-portal-frontend-v2:latest
  env:
    - name: API_URL
      value: https://kunde-beta.felleskomponent.no
  url:
    hostname: kunde-remix.felleskomponent.no
    basePath: /
  ingress:
    enabled: true
    middlewares:
      - fint-kunde-portal-v2-sso